# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AwkDate' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AwkDate
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'MessageKit'
  pod 'MessageInputBar'

  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/AdMob'
  pod 'Firebase/Messaging'
  
  target 'AwkDateTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AwkDateUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
